# .github/workflows/deploy.yml

name: Deploy things
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:    
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Prepare for deployment
      uses: actions/checkout@master
    - name: Download PHP
      uses: actions/download-artifact@v1
      with:
        name: php-build
        path: vendor
    - name: Deploy website
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}/httpdocs
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        args: --only-newer --ignore-time --verbose
    - if: success()
      name: Send deployment success message
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Git message
        SLACK_MESSAGE: The deployment process succeeded
    - if: failure()
      name: Send deployment fail message
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Git message
        SLACK_MESSAGE: The deployment process failed
        SLACK_COLOR: '#BE2625'