# .github/workflows/main.yml

name: Production CI
on:
  push:
    branches:
    - master

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files and setup environment
      uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - name: Build plugins
      run: composer update
    - name: Build assets
      run: yarn && yarn production
    - name: Upload PHP
      uses: actions/upload-artifact@v1
      with:
        name: php-build
        path: vendor
    - if: success()
      name: Send build success message
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Git message
        SLACK_MESSAGE: The build process succeeded
    - if: failure()
      name: Send build fail message
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Git message
        SLACK_MESSAGE: The build process failed
        SLACK_COLOR: '#BE2625'

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Prepare for deployment
      uses: actions/checkout@master
    - name: Download PHP
      uses: actions/download-artifact@v1
      with:
        name: php-build
        path: vendor
    - name: Deploy website
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --remote-root=httpdocs
        args: --only-newer --ignore-time --verbose
    - if: success()
      name: Send deployment success message
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Git message
        SLACK_MESSAGE: The deployment process succeeded
    - if: failure()
      name: Send deployment fail message
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Git message
        SLACK_MESSAGE: The deployment process failed
        SLACK_COLOR: '#BE2625'
